def digestive_support_options():
    print("=" * 70)
    print("DIGESTIVE SUPPORT FOR CHRONIC GAS OR MILD INFLAMMATION")
    print("=" * 70)
    print()

    # -------------------- BANANAS --------------------
    print("1. 1–2 RIPE BANANAS")
    print("-" * 40)
    print("Ripe bananas are a gentle, practical choice for many people")
    print("dealing with gas or mild inflammation.")
    print()
    print("They supply:")
    print("  • Soluble fiber (mainly pectin)")
    print("      – Softens stool and supports regular transit")
    print("  • Resistant starch (higher in slightly less-ripe bananas)")
    print("      – Feeds beneficial gut bacteria")
    print("  • Potassium and easy-to-digest carbohydrates")
    print("      – Help calm an irritated digestive tract")
    print()
    print("Practical guidance:")
    print("  • 1–2 medium ripe bananas per day is well tolerated by most people")
    print("  • Can reduce the feeling of incomplete digestion")
    print("  • If gas increases with resistant starch → choose fully yellow")
    print("    bananas with a few brown spots (lower fermentable material, gentler)")
    print()
    print("Tip: Chew thoroughly to continue the mechanical-breakdown principle")
    print("     from the oral-hygiene routine.")
    print()

    # -------------------- SOLUBLE FIBER --------------------
    print("2. ONE TEASPOON OF SOLUBLE FIBER MIXED WITH WATER")
    print("-" * 40)
    print("This matches the powder + water setup shown in the photo.")
    print()
    print("Recommended true soluble fibers:")
    print("  • Psyllium husk (most studied)")
    print("  • Methylcellulose")
    print("  • Partially hydrolyzed guar gum")
    print()
    print("PROPER SOLUBLE MIXTURE METHOD (\"True Proper Soluble Mixture\"):")
    print("  1. Measure 1 level teaspoon (not heaping) of fiber powder")
    print("  2. Mix into ½ to 1 cup (120–240 ml) of water")
    print("  3. Stir vigorously for 15–30 seconds until smooth")
    print("     and slightly thickened with no dry clumps")
    print("  4. Drink immediately (fibers continue to gel if left sitting)")
    print("  5. Follow with another full glass of plain water")
    print()
    print("Why this ratio matters:")
    print("  • 1 tsp fiber + ½–1 cup water is the standard effective mixture")
    print("  • Too little water lets the fiber swell inside the gut")
    print("    and can temporarily increase gas or bloating")
    print()
    print("Physiological benefits:")
    print("  • Forms a soft gel that normalizes stool consistency")
    print("  • Slows excessive fermentation")
    print("  • Improves transit time and reduces gas production window")
    print("  • Supports a healthier gut mucosal barrier")
    print()

    print("=" * 70)
    print("Both options complement the multi-pass brushing routine and")
    print("strategic raw-broccoli intake for overall gut and systemic support.")
    print("=" * 70)


# Run the function
digestive_support_options()
